edition = "2021"

# Stable.
reorder_modules = false
use_small_heuristics = "Max"
max_width = 100
use_field_init_shorthand = true

# Unstable (requires nightly rust).
# imports_layout = "Vertical"
comment_width = 200
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = true
